"""add location_type to posts

Revision ID: 00b5c117309a
Revises: 61c0fbb8589e
Create Date: 2026-02-15 23:55:09.244815

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "00b5c117309a"
down_revision = "61c0fbb8589e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("location_type", sa.String(length=20), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("location_type")

    # ### end Alembic commands ###
