"""add title and event_type to posts

Revision ID: a72e0dc3578f
Revises: dc1c57e60b96
Create Date: 2026-02-15 23:12:49.777146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a72e0dc3578f'
down_revision = 'dc1c57e60b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('event_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=2000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)
        batch_op.drop_column('event_type')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
