"""add_is_admin_to_user_add_tournament_add_registration

Revision ID: c53d4ca59be7
Revises: 2c12e32ad1de
Create Date: 2026-08-20 16:57:31.374255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c53d4ca59be7'
down_revision = '2c12e32ad1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('ingame_name', sa.String(length=64), nullable=False),
    sa.Column('club_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registration_tournament_id'), ['tournament_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registration_tournament_id'))

    op.drop_table('registration')
    op.drop_table('tournament')
    # ### end Alembic commands ###
