"""add event table

Revision ID: dc1c57e60b96
Revises: e84d843b7aa0
Create Date: 2026-02-15 19:18:41.268441

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dc1c57e60b96"
down_revision = "e84d843b7aa0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("location", sa.String(length=100), nullable=False),
        sa.Column("event_time", sa.DateTime(), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event")
    # ### end Alembic commands ###
